FctBundle\Entity\Fct:
    type: entity
    table: fct
    indexes:
        f_keyAlumnos:
            columns:
                - id_alumno
        f_keyProf:
            columns:
                - id_profesor
        f_keyEmp:
            columns:
                - id_empresa
    id:
        codFct:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: cod_fct
            generator:
                strategy: IDENTITY
    fields:
        fecha:
            type: date
            nullable: false
    manyToOne:
        idAlumno:
            targetEntity: Alumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_alumno:
                    referencedColumnName: id_alumno
            orphanRemoval: false
        idEmpresa:
            targetEntity: Empresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_empresa:
                    referencedColumnName: id_empresa
            orphanRemoval: false
        idProfesor:
            targetEntity: Profesor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_profesor:
                    referencedColumnName: id_profesor
            orphanRemoval: false
    lifecycleCallbacks: {  }
