FctBundle\Entity\Fct:
    type: entity
    table: fct
    indexes:
        FK_FCT2:
            columns:
                - CIF_EMP
        FK_FCT3:
            columns:
                - NIF_ALU
        IDX_AAA3E3C1A78FCC64:
            columns:
                - NIF_PROF
    id: {  }
    fields:
        anio:
            type: decimal
            nullable: true
            precision: 4
            scale: 0
            column: ANIO
    oneToOne:
        nifProf:
            targetEntity: Profesor
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                NIF_PROF:
                    referencedColumnName: NIF_PROF
            orphanRemoval: false
        cifEmp:
            targetEntity: Empresa
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CIF_EMP:
                    referencedColumnName: CIF_EMP
            orphanRemoval: false
        nifAlu:
            targetEntity: Alumno
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                NIF_ALU:
                    referencedColumnName: NIF_ALU
            orphanRemoval: false
    lifecycleCallbacks: {  }
