FctBundle\Entity\Usuario:
    type: entity
    table: usuarios
    uniqueConstraints:
        NICKNAME_USER:
            columns:
                - NICKNAME_USER
        PASSWORD_USER:
            columns:
                - PASSWORD_USER
    id:
        nifUser:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            id: true
            column: NIF_USER
            generator:
                strategy: IDENTITY
    fields:
        nombreUser:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: NOMBRE_USER
        apellido1User:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APELLIDO1_USER
        apellido2User:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: APELLIDO2_USER
        fotografiaUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: FOTOGRAFIA_USER
        nicknameUser:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: NICKNAME_USER
        telfFijoUser:
            type: decimal
            nullable: true
            precision: 9
            scale: 0
            column: TELF_FIJO_USER
        telfMovilUser:
            type: decimal
            nullable: true
            precision: 9
            scale: 0
            column: TELF_MOVIL_USER
        emailUser:
            type: string
            nullable: true
            length: 25
            options:
                fixed: false
            column: EMAIL_USER
        passwordUser:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
            column: PASSWORD_USER
        rolUser:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
            column: ROL_USER
    lifecycleCallbacks: {  }
