FCTBundle\Entity\Alumno:
    type: entity
    table: alumno
    indexes:
        f_keyCiclo:
            columns:
                - cod_ciclo
    id:
        dni:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        ape1:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        ape2:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        nick:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        direccion:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        poblacion:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        cp:
            type: string
            nullable: false
            length: 5
            options:
                fixed: false
        provincia:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        tlffijo:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: tlfFijo
        tlfmovil:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: tlfMovil
        email:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        foto:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    manyToOne:
        codCiclo:
            targetEntity: Ciclo
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                cod_ciclo:
                    referencedColumnName: cod_ciclo
            orphanRemoval: false
    lifecycleCallbacks: {  }
