FCTBundle\Entity\Profesor:
    type: entity
    table: profesor
    id:
        dni:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nombre:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        ape1:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        ape2:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        nick:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        tlf:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 30
            options:
                fixed: false
        foto:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
