FCTBundle\Entity\Usuario:
    type: entity
    table: usuario
    id:
        dni:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tipo:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        ape1:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        ape2:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        nick:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
        tlffijo:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: tlfFijo
        tlfmovil:
            type: string
            nullable: false
            length: 9
            options:
                fixed: false
            column: tlfMovil
        email:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        foto:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
    lifecycleCallbacks: {  }
